// 전국 시·군 사전 — build-cluster-intents(잠금 장부)와 next-wave(다음 물결 레이더)가 함께 쓴다.

/**
 * 전국 시·군(8도 + 제주). T1은 "방금 가결된 지자체"가 매일 새로 생기는 트랙이라(계획 §2·§3)
 * 사전 밖 지자체가 기본 경우다 — 사전이 없으면 `--append`가 지역을 못 찾고 잠금이 빠진다.
 * 형식: [로마자 id, 이름, 접미사]. 별칭은 "이름+접미사"(합천군)이고, 특례시는 'X특례시'를 더한다.
 * 같은 이름이 build-cluster-intents의 EXTRA_REGIONS·regions.json에 있으면 그쪽이 우선한다(고성은 강원·경남 둘 다 '고성' 하나).
 * 광역시 자치구는 이름이 너무 흔해(중구·남구) 넣지 않는다 — 필요하면 EXTRA_REGIONS에 별칭과 함께.
 */
export const NATIONWIDE = [
  // 경기
  ['suwon', '수원', '시'],
  ['seongnam', '성남', '시'],
  ['goyang', '고양', '시'],
  ['yongin', '용인', '시'],
  ['bucheon', '부천', '시'],
  ['ansan', '안산', '시'],
  ['anyang', '안양', '시'],
  ['namyangju', '남양주', '시'],
  ['pyeongtaek', '평택', '시'],
  ['uijeongbu', '의정부', '시'],
  ['siheung', '시흥', '시'],
  ['paju', '파주', '시'],
  ['gwangmyeong', '광명', '시'],
  ['gimpo', '김포', '시'],
  ['gunpo', '군포', '시'],
  ['icheon', '이천', '시'],
  ['yangju', '양주', '시'],
  ['osan', '오산', '시'],
  ['guri', '구리', '시'],
  ['anseong', '안성', '시'],
  ['pocheon', '포천', '시'],
  ['uiwang', '의왕', '시'],
  ['hanam', '하남', '시'],
  ['yeoju', '여주', '시'],
  ['dongducheon', '동두천', '시'],
  ['gwacheon', '과천', '시'],
  ['yeoncheon', '연천', '군'],
  ['gapyeong', '가평', '군'],
  ['yangpyeong', '양평', '군'],
  // 강원
  ['chuncheon', '춘천', '시'],
  ['wonju', '원주', '시'],
  ['donghae', '동해', '시'],
  ['taebaek', '태백', '시'],
  ['samcheok', '삼척', '시'],
  ['hongcheon', '홍천', '군'],
  ['hoengseong', '횡성', '군'],
  ['yeongwol', '영월', '군'],
  ['pyeongchang', '평창', '군'],
  ['cheorwon', '철원', '군'],
  ['hwacheon', '화천', '군'],
  ['yanggu', '양구', '군'],
  ['inje', '인제', '군'],
  // 충북
  ['chungju', '충주', '시'],
  ['jecheon', '제천', '시'],
  ['boeun', '보은', '군'],
  ['okcheon', '옥천', '군'],
  ['jeungpyeong', '증평', '군'],
  ['jincheon', '진천', '군'],
  ['goesan', '괴산', '군'],
  ['eumseong', '음성', '군'],
  ['danyang', '단양', '군'],
  // 충남
  ['cheonan', '천안', '시'],
  ['gongju', '공주', '시'],
  ['boryeong', '보령', '시'],
  ['asan', '아산', '시'],
  ['seosan', '서산', '시'],
  ['nonsan', '논산', '시'],
  ['gyeryong', '계룡', '시'],
  ['geumsan', '금산', '군'],
  ['buyeo', '부여', '군'],
  ['seocheon', '서천', '군'],
  ['hongseong', '홍성', '군'],
  ['yesan', '예산', '군'],
  ['taean', '태안', '군'],
  // 전북
  ['jeonju', '전주', '시'],
  ['gunsan', '군산', '시'],
  ['iksan', '익산', '시'],
  ['namwon', '남원', '시'],
  ['gimje', '김제', '시'],
  ['jinan', '진안', '군'],
  ['muju', '무주', '군'],
  ['jangsu', '장수', '군'],
  ['imsil', '임실', '군'],
  ['sunchang', '순창', '군'],
  // 전남
  ['mokpo', '목포', '시'],
  ['yeosu', '여수', '시'],
  ['suncheon', '순천', '시'],
  ['damyang', '담양', '군'],
  ['gokseong', '곡성', '군'],
  ['gurye', '구례', '군'],
  ['boseong', '보성', '군'],
  ['hwasun', '화순', '군'],
  ['gangjin', '강진', '군'],
  ['muan', '무안', '군'],
  ['yeonggwang', '영광', '군'],
  ['wando', '완도', '군'],
  ['sinan', '신안', '군'],
  // 경북
  ['pohang', '포항', '시'],
  ['gyeongju', '경주', '시'],
  ['gimcheon', '김천', '시'],
  ['andong', '안동', '시'],
  ['gumi', '구미', '시'],
  ['yeongju', '영주', '시'],
  ['sangju', '상주', '시'],
  ['gyeongsan', '경산', '시'],
  ['gunwi', '군위', '군'],
  ['cheongsong', '청송', '군'],
  ['yeongyang', '영양', '군'],
  ['cheongdo', '청도', '군'],
  ['goryeong', '고령', '군'],
  ['seongju', '성주', '군'],
  ['chilgok', '칠곡', '군'],
  ['yecheon', '예천', '군'],
  ['bonghwa', '봉화', '군'],
  ['ulleung', '울릉', '군'],
  // 경남
  ['jinju', '진주', '시'],
  ['sacheon', '사천', '시'],
  ['miryang', '밀양', '시'],
  ['geoje', '거제', '시'],
  ['haman', '함안', '군'],
  ['changnyeong', '창녕', '군'],
  ['namhae', '남해', '군'],
  ['sancheong', '산청', '군'],
  ['hamyang', '함양', '군'],
  ['hapcheon', '합천', '군'],
  // 제주
  ['seogwipo', '서귀포', '시'],
];
